server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/donaton_logistics
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.docker.compose.enabled=false

logistics.acopio.deadline-days=3
logistics.acopio.expire-check-ms=3600000

donation.base-url=http://donation:8080
needs.base-url=http://needs:8080