server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: http://auth:8080
              predicates:
                - Path=/auth/**

            - id: bff
              uri: http://bff:8081
              predicates:
                - Path=/bff/**

          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins:
                  - "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                allowedHeaders:
                  - "*"
                allowCredentials: false

jwt:
  secret: mi_clave_secreta_muy_larga_para_hs256_segura_12345
  expiration: 86400000
