spring.application.name=donation-service

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/donaton_donation
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

needs.base-url=http://needs:8080
logistics.base-url=http://logistics:8080