server:
  port: 8081

spring:
  application:
    name: bff

  profiles:
    active: local

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: basic

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${jwt.secret}

jwt:
  secret: mi_clave_secreta_muy_larga_para_hs256_segura_12345

bff:
  security:
    public-paths:
      - /api/v1/auth/login
      - /api/v1/auth/register
      - /api/v1/auth/refresh
      - /actuator/health

logging:
  level:
    com.bff: INFO
    org.springframework.security: INFO
    org.springframework.cloud.openfeign: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: http://localhost:8081
          donation-service:
            url: http://localhost:8082
          logistics-service:
            url: http://localhost:8083
          needs-service:
            url: http://localhost:8084
---
spring:
  config:
    activate:
      on-profile: docker

  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: http://auth:8080
          donation-service:
            url: http://donation:8080
          logistics-service:
            url: http://logistics:8080
          needs-service:
            url: http://needs:8080
