name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth, donation, logistics, needs, gateway]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: mvn -B clean install
